addSbtPlugin("org.scoverage" % "sbt-scoverage"  % "1.6.1")
addSbtPlugin("org.scalameta" % "sbt-scalafmt"   % "2.4.0")
addSbtPlugin("com.geirsson"  % "sbt-ci-release" % "1.5.3")
addSbtPlugin("ch.epfl.scala" % "sbt-bloop"      % "1.4.2")
addSbtPlugin("org.scalameta" % "sbt-mdoc"       % "2.1.5")
addSbtPlugin("com.eed3si9n"  % "sbt-unidoc"     % "0.4.3")
