addSbtPlugin("org.scoverage" % "sbt-scoverage"  % "1.8.1")
addSbtPlugin("org.scalameta" % "sbt-scalafmt"   % "2.4.0")
addSbtPlugin("com.geirsson"  % "sbt-ci-release" % "1.5.5")
addSbtPlugin("ch.epfl.scala" % "sbt-bloop"      % "1.4.8")
addSbtPlugin("org.scalameta" % "sbt-mdoc"       % "2.2.21")
addSbtPlugin("com.eed3si9n"  % "sbt-unidoc"     % "0.4.3")
